# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.2.dev2+g7b1cbc9.d20230710'
__version_tuple__ = version_tuple = (0, 0, 2, 'dev2', 'g7b1cbc9.d20230710')
