
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-09T10:32:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a597009695ed2fe5fcf787b0e31dbee38e301bf3",
 "version": "2.0.0b25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
