# This file was auto-generated by Fern from our API Definition.

import enum


class MergeApiEnvironment(enum.Enum):
    PRODUCTION = "https://api.merge.dev"
    SANDBOX = "https://api-sandbox.merge.dev"
