# coding: utf-8

"""
    Creditas OpenAPI

    This is specification of the Creditas OpenAPI. It contains definitions of Creditas banking services exposed via API accessible on the internet.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: is@creditas.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import creditas
from creditas.models.inline_response20017 import InlineResponse20017  # noqa: E501
from creditas.rest import ApiException


class TestInlineResponse20017(unittest.TestCase):
    """InlineResponse20017 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20017(self):
        """Test InlineResponse20017"""
        # FIXME: construct object with mandatory attributes with example values
        # model = creditas.models.inline_response20017.InlineResponse20017()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
