# coding: utf-8

"""
    Creditas OpenAPI

    This is specification of the Creditas OpenAPI. It contains definitions of Creditas banking services exposed via API accessible on the internet.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: is@creditas.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import creditas
from creditas.api.statement_api import StatementApi  # noqa: E501
from creditas.rest import ApiException


class TestStatementApi(unittest.TestCase):
    """StatementApi unit test stubs"""

    def setUp(self):
        self.api = creditas.api.statement_api.StatementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_s_ta_account_statement_get_api(self):
        """Test case for s_ta_account_statement_get_api

        Download account statement  # noqa: E501
        """
        pass

    def test_s_ta_account_statement_list_api(self):
        """Test case for s_ta_account_statement_list_api

        Get list of available account satements  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
