
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-07T11:01:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "56f2fbc5b779cac8ad5e59861e1ce1c4ed220330",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
