"""
    Data Modelling Storage Service

    API for basic data modelling interaction  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dmss_api
from dmss_api.model.access_level import AccessLevel
globals()['AccessLevel'] = AccessLevel
from dmss_api.model.acl import ACL


class TestACL(unittest.TestCase):
    """ACL unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testACL(self):
        """Test ACL"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ACL()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
