# Generated by Django 4.1.9 on 2023-06-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_cisco_support_plugin", "0004_ciscodevicesupport_name_ciscodevicetypesupport_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciscodevicesupport",
            name="partner_coverage_end_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ciscodevicesupport",
            name="partner_customer_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ciscodevicesupport",
            name="partner_service_level",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ciscodevicesupport",
            name="partner_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
