# flake8: noqa
from cherre_singer_ingest.value_items.ingest_bookmarks.bookmark_type import BookmarkTypes
from cherre_singer_ingest.value_items.ingest_bookmarks.ingest_bookmark import IngestBookmark
from cherre_singer_ingest.value_items.ingest_bookmarks.file_read_bookmark import FileReadBookmark
from cherre_singer_ingest.value_items.ingest_bookmarks.file_read_failed_bookmark import FileReadFailedBookmark
from cherre_singer_ingest.value_items.ingest_bookmarks.file_unzipped_bookmark import FileUnzippedBookmark
from cherre_singer_ingest.value_items.ingest_bookmarks.file_unzipped_failed_bookmark import FileUnzippedFailedBookmark
from cherre_singer_ingest.value_items.ingest_bookmarks.uri_bookmark import UriBookmark
