# noinspection DuplicatedCode
TEAMS = {
    "ANA": {
        "abbreviation": "ANA",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 15, "link": "/api/v1/divisions/15", "name": "Pacific"},
        "firstYearOfPlay": "1993",
        "franchise": {
            "franchiseId": 32,
            "link": "/api/v1/franchises/32",
            "teamName": "Ducks",
        },
        "franchiseId": 32,
        "id": 24,
        "link": "/api/v1/teams/24",
        "locationName": "Anaheim",
        "name": "Anaheim Ducks",
        "officialSiteUrl": "http://www.anaheimducks.com",
        "shortName": "Anaheim",
        "teamName": "Ducks",
        "venue": {
            "city": "Anaheim",
            "link": "/api/v1/venues/null",
            "name": "Honda Center",
            "timeZone": {"id": "America/Los_Angeles", "offset": -8, "tz": "PST"},
        },
    },
    "ARI": {
        "abbreviation": "ARI",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 15, "link": "/api/v1/divisions/15", "name": "Pacific"},
        "firstYearOfPlay": "1979",
        "franchise": {
            "franchiseId": 28,
            "link": "/api/v1/franchises/28",
            "teamName": "Coyotes",
        },
        "franchiseId": 28,
        "id": 53,
        "link": "/api/v1/teams/53",
        "locationName": "Arizona",
        "name": "Arizona Coyotes",
        "officialSiteUrl": "http://www.arizonacoyotes.com",
        "shortName": "Arizona",
        "teamName": "Coyotes",
        "venue": {
            "city": "Glendale",
            "link": "/api/v1/venues/null",
            "name": "Gila River Arena",
            "timeZone": {"id": "America/Phoenix", "offset": -7, "tz": "MST"},
        },
    },
    "BOS": {
        "abbreviation": "BOS",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 17, "link": "/api/v1/divisions/17", "name": "Atlantic"},
        "firstYearOfPlay": "1924",
        "franchise": {
            "franchiseId": 6,
            "link": "/api/v1/franchises/6",
            "teamName": "Bruins",
        },
        "franchiseId": 6,
        "id": 6,
        "link": "/api/v1/teams/6",
        "locationName": "Boston",
        "name": "Boston Bruins",
        "officialSiteUrl": "http://www.bostonbruins.com",
        "shortName": "Boston",
        "teamName": "Bruins",
        "venue": {
            "city": "Boston",
            "link": "/api/v1/venues/null",
            "name": "TD Garden",
            "timeZone": {"id": "America/New_York", "offset": -5, "tz": "EST"},
        },
    },
    "BUF": {
        "abbreviation": "BUF",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 17, "link": "/api/v1/divisions/17", "name": "Atlantic"},
        "firstYearOfPlay": "1970",
        "franchise": {
            "franchiseId": 19,
            "link": "/api/v1/franchises/19",
            "teamName": "Sabres",
        },
        "franchiseId": 19,
        "id": 7,
        "link": "/api/v1/teams/7",
        "locationName": "Buffalo",
        "name": "Buffalo Sabres",
        "officialSiteUrl": "http://www.sabres.com",
        "shortName": "Buffalo",
        "teamName": "Sabres",
        "venue": {
            "city": "Buffalo",
            "link": "/api/v1/venues/null",
            "name": "KeyBank Center",
            "timeZone": {"id": "America/New_York", "offset": -5, "tz": "EST"},
        },
    },
    "CAR": {
        "abbreviation": "CAR",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 18, "link": "/api/v1/divisions/18", "name": "Metropolitan"},
        "firstYearOfPlay": "1979",
        "franchise": {
            "franchiseId": 26,
            "link": "/api/v1/franchises/26",
            "teamName": "Hurricanes",
        },
        "franchiseId": 26,
        "id": 12,
        "link": "/api/v1/teams/12",
        "locationName": "Carolina",
        "name": "Carolina Hurricanes",
        "officialSiteUrl": "http://www.carolinahurricanes.com",
        "shortName": "Carolina",
        "teamName": "Hurricanes",
        "venue": {
            "city": "Raleigh",
            "link": "/api/v1/venues/null",
            "name": "PNC Arena",
            "timeZone": {"id": "America/New_York", "offset": -5, "tz": "EST"},
        },
    },
    "CBJ": {
        "abbreviation": "CBJ",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 18, "link": "/api/v1/divisions/18", "name": "Metropolitan"},
        "firstYearOfPlay": "1997",
        "franchise": {
            "franchiseId": 36,
            "link": "/api/v1/franchises/36",
            "teamName": "Blue Jackets",
        },
        "franchiseId": 36,
        "id": 29,
        "link": "/api/v1/teams/29",
        "locationName": "Columbus",
        "name": "Columbus Blue Jackets",
        "officialSiteUrl": "http://www.bluejackets.com",
        "shortName": "Columbus",
        "teamName": "Blue Jackets",
        "venue": {
            "city": "Columbus",
            "link": "/api/v1/venues/null",
            "name": "Nationwide Arena",
            "timeZone": {"id": "America/New_York", "offset": -5, "tz": "EST"},
        },
    },
    "CGY": {
        "abbreviation": "CGY",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 15, "link": "/api/v1/divisions/15", "name": "Pacific"},
        "firstYearOfPlay": "1980",
        "franchise": {
            "franchiseId": 21,
            "link": "/api/v1/franchises/21",
            "teamName": "Flames",
        },
        "franchiseId": 21,
        "id": 20,
        "link": "/api/v1/teams/20",
        "locationName": "Calgary",
        "name": "Calgary Flames",
        "officialSiteUrl": "http://www.calgaryflames.com",
        "shortName": "Calgary",
        "teamName": "Flames",
        "venue": {
            "city": "Calgary",
            "link": "/api/v1/venues/null",
            "name": "Scotiabank Saddledome",
            "timeZone": {"id": "America/Denver", "offset": -7, "tz": "MST"},
        },
    },
    "CHI": {
        "abbreviation": "CHI",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 16, "link": "/api/v1/divisions/16", "name": "Central"},
        "firstYearOfPlay": "1926",
        "franchise": {
            "franchiseId": 11,
            "link": "/api/v1/franchises/11",
            "teamName": "Blackhawks",
        },
        "franchiseId": 11,
        "id": 16,
        "link": "/api/v1/teams/16",
        "locationName": "Chicago",
        "name": "Chicago Blackhawks",
        "officialSiteUrl": "http://www.chicagoblackhawks.com",
        "shortName": "Chicago",
        "teamName": "Blackhawks",
        "venue": {
            "city": "Chicago",
            "link": "/api/v1/venues/null",
            "name": "United Center",
            "timeZone": {"id": "America/Chicago", "offset": -6, "tz": "CST"},
        },
    },
    "COL": {
        "abbreviation": "COL",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 16, "link": "/api/v1/divisions/16", "name": "Central"},
        "firstYearOfPlay": "1979",
        "franchise": {
            "franchiseId": 27,
            "link": "/api/v1/franchises/27",
            "teamName": "Avalanche",
        },
        "franchiseId": 27,
        "id": 21,
        "link": "/api/v1/teams/21",
        "locationName": "Colorado",
        "name": "Colorado Avalanche",
        "officialSiteUrl": "http://www.coloradoavalanche.com",
        "shortName": "Colorado",
        "teamName": "Avalanche",
        "venue": {
            "city": "Denver",
            "link": "/api/v1/venues/null",
            "name": "Pepsi Center",
            "timeZone": {"id": "America/Denver", "offset": -7, "tz": "MST"},
        },
    },
    "DAL": {
        "abbreviation": "DAL",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 16, "link": "/api/v1/divisions/16", "name": "Central"},
        "firstYearOfPlay": "1967",
        "franchise": {
            "franchiseId": 15,
            "link": "/api/v1/franchises/15",
            "teamName": "Stars",
        },
        "franchiseId": 15,
        "id": 25,
        "link": "/api/v1/teams/25",
        "locationName": "Dallas",
        "name": "Dallas Stars",
        "officialSiteUrl": "http://www.dallasstars.com",
        "shortName": "Dallas",
        "teamName": "Stars",
        "venue": {
            "city": "Dallas",
            "link": "/api/v1/venues/null",
            "name": "American Airlines Center",
            "timeZone": {"id": "America/Chicago", "offset": -6, "tz": "CST"},
        },
    },
    "DET": {
        "abbreviation": "DET",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 17, "link": "/api/v1/divisions/17", "name": "Atlantic"},
        "firstYearOfPlay": "1926",
        "franchise": {
            "franchiseId": 12,
            "link": "/api/v1/franchises/12",
            "teamName": "Red Wings",
        },
        "franchiseId": 12,
        "id": 17,
        "link": "/api/v1/teams/17",
        "locationName": "Detroit",
        "name": "Detroit Red Wings",
        "officialSiteUrl": "http://www.detroitredwings.com",
        "shortName": "Detroit",
        "teamName": "Red Wings",
        "venue": {
            "city": "Detroit",
            "link": "/api/v1/venues/null",
            "name": "Little Caesars Arena",
            "timeZone": {"id": "America/Detroit", "offset": -5, "tz": "EST"},
        },
    },
    "EDM": {
        "abbreviation": "EDM",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 15, "link": "/api/v1/divisions/15", "name": "Pacific"},
        "firstYearOfPlay": "1979",
        "franchise": {
            "franchiseId": 25,
            "link": "/api/v1/franchises/25",
            "teamName": "Oilers",
        },
        "franchiseId": 25,
        "id": 22,
        "link": "/api/v1/teams/22",
        "locationName": "Edmonton",
        "name": "Edmonton Oilers",
        "officialSiteUrl": "http://www.edmontonoilers.com",
        "shortName": "Edmonton",
        "teamName": "Oilers",
        "venue": {
            "city": "Edmonton",
            "link": "/api/v1/venues/null",
            "name": "Rogers Place",
            "timeZone": {"id": "America/Edmonton", "offset": -7, "tz": "MST"},
        },
    },
    "FLA": {
        "abbreviation": "FLA",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 17, "link": "/api/v1/divisions/17", "name": "Atlantic"},
        "firstYearOfPlay": "1993",
        "franchise": {
            "franchiseId": 33,
            "link": "/api/v1/franchises/33",
            "teamName": "Panthers",
        },
        "franchiseId": 33,
        "id": 13,
        "link": "/api/v1/teams/13",
        "locationName": "Florida",
        "name": "Florida Panthers",
        "officialSiteUrl": "http://www.floridapanthers.com",
        "shortName": "Florida",
        "teamName": "Panthers",
        "venue": {
            "city": "Sunrise",
            "link": "/api/v1/venues/null",
            "name": "BB&T Center",
            "timeZone": {"id": "America/New_York", "offset": -5, "tz": "EST"},
        },
    },
    "LAK": {
        "abbreviation": "LAK",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 15, "link": "/api/v1/divisions/15", "name": "Pacific"},
        "firstYearOfPlay": "1967",
        "franchise": {
            "franchiseId": 14,
            "link": "/api/v1/franchises/14",
            "teamName": "Kings",
        },
        "franchiseId": 14,
        "id": 26,
        "link": "/api/v1/teams/26",
        "locationName": "Los Angeles",
        "name": "Los Angeles Kings",
        "officialSiteUrl": "http://www.lakings.com",
        "shortName": "Los Angeles",
        "teamName": "Kings",
        "venue": {
            "city": "Los Angeles",
            "link": "/api/v1/venues/null",
            "name": "STAPLES Center",
            "timeZone": {"id": "America/Los_Angeles", "offset": -8, "tz": "PST"},
        },
    },
    "MIN": {
        "abbreviation": "MIN",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 16, "link": "/api/v1/divisions/16", "name": "Central"},
        "firstYearOfPlay": "1997",
        "franchise": {
            "franchiseId": 37,
            "link": "/api/v1/franchises/37",
            "teamName": "Wild",
        },
        "franchiseId": 37,
        "id": 30,
        "link": "/api/v1/teams/30",
        "locationName": "Minnesota",
        "name": "Minnesota Wild",
        "officialSiteUrl": "http://www.wild.com",
        "shortName": "Minnesota",
        "teamName": "Wild",
        "venue": {
            "city": "St. Paul",
            "link": "/api/v1/venues/null",
            "name": "Xcel Energy Center",
            "timeZone": {"id": "America/Chicago", "offset": -6, "tz": "CST"},
        },
    },
    "MTL": {
        "abbreviation": "MTL",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 17, "link": "/api/v1/divisions/17", "name": "Atlantic"},
        "firstYearOfPlay": "1909",
        "franchise": {
            "franchiseId": 1,
            "link": "/api/v1/franchises/1",
            "teamName": "Canadiens",
        },
        "franchiseId": 1,
        "id": 8,
        "link": "/api/v1/teams/8",
        "locationName": "Montr\u00e9al",
        "name": "Montr\u00e9al Canadiens",
        "officialSiteUrl": "http://www.canadiens.com",
        "shortName": "Montr\u00e9al",
        "teamName": "Canadiens",
        "venue": {
            "city": "Montreal",
            "link": "/api/v1/venues/null",
            "name": "Centre Bell",
            "timeZone": {"id": "America/Montreal", "offset": -5, "tz": "EST"},
        },
    },
    "NJD": {
        "abbreviation": "NJD",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 18, "link": "/api/v1/divisions/18", "name": "Metropolitan"},
        "firstYearOfPlay": "1982",
        "franchise": {
            "franchiseId": 23,
            "link": "/api/v1/franchises/23",
            "teamName": "Devils",
        },
        "franchiseId": 23,
        "id": 1,
        "link": "/api/v1/teams/1",
        "locationName": "New Jersey",
        "name": "New Jersey Devils",
        "officialSiteUrl": "http://www.Truesince82.com",
        "shortName": "New Jersey",
        "teamName": "Devils",
        "venue": {
            "city": "Newark",
            "link": "/api/v1/venues/null",
            "name": "Prudential Center",
            "timeZone": {"id": "America/New_York", "offset": -5, "tz": "EST"},
        },
    },
    "NSH": {
        "abbreviation": "NSH",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 16, "link": "/api/v1/divisions/16", "name": "Central"},
        "firstYearOfPlay": "1997",
        "franchise": {
            "franchiseId": 34,
            "link": "/api/v1/franchises/34",
            "teamName": "Predators",
        },
        "franchiseId": 34,
        "id": 18,
        "link": "/api/v1/teams/18",
        "locationName": "Nashville",
        "name": "Nashville Predators",
        "officialSiteUrl": "http://www.nashvillepredators.com",
        "shortName": "Nashville",
        "teamName": "Predators",
        "venue": {
            "city": "Nashville",
            "link": "/api/v1/venues/null",
            "name": "Bridgestone Arena",
            "timeZone": {"id": "America/Chicago", "offset": -6, "tz": "CST"},
        },
    },
    "NYI": {
        "abbreviation": "NYI",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 18, "link": "/api/v1/divisions/18", "name": "Metropolitan"},
        "firstYearOfPlay": "1972",
        "franchise": {
            "franchiseId": 22,
            "link": "/api/v1/franchises/22",
            "teamName": "Islanders",
        },
        "franchiseId": 22,
        "id": 2,
        "link": "/api/v1/teams/2",
        "locationName": "New York",
        "name": "New York Islanders",
        "officialSiteUrl": "http://www.newyorkislanders.com",
        "shortName": "NY Islanders",
        "teamName": "Islanders",
        "venue": {
            "city": "Brooklyn",
            "link": "/api/v1/venues/null",
            "name": "Barclays Center",
            "timeZone": {"id": "America/New_York", "offset": -5, "tz": "EST"},
        },
    },
    "NYR": {
        "abbreviation": "NYR",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 18, "link": "/api/v1/divisions/18", "name": "Metropolitan"},
        "firstYearOfPlay": "1926",
        "franchise": {
            "franchiseId": 10,
            "link": "/api/v1/franchises/10",
            "teamName": "Rangers",
        },
        "franchiseId": 10,
        "id": 3,
        "link": "/api/v1/teams/3",
        "locationName": "New York",
        "name": "New York Rangers",
        "officialSiteUrl": "http://www.newyorkrangers.com",
        "shortName": "NY Rangers",
        "teamName": "Rangers",
        "venue": {
            "city": "New York",
            "link": "/api/v1/venues/null",
            "name": "Madison Square Garden",
            "timeZone": {"id": "America/New_York", "offset": -5, "tz": "EST"},
        },
    },
    "OTT": {
        "abbreviation": "OTT",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 17, "link": "/api/v1/divisions/17", "name": "Atlantic"},
        "firstYearOfPlay": "1990",
        "franchise": {
            "franchiseId": 30,
            "link": "/api/v1/franchises/30",
            "teamName": "Senators",
        },
        "franchiseId": 30,
        "id": 9,
        "link": "/api/v1/teams/9",
        "locationName": "Ottawa",
        "name": "Ottawa Senators",
        "officialSiteUrl": "http://www.ottawasenators.com",
        "shortName": "Ottawa",
        "teamName": "Senators",
        "venue": {
            "city": "Ottawa",
            "link": "/api/v1/venues/null",
            "name": "Canadian Tire Centre",
            "timeZone": {"id": "America/New_York", "offset": -5, "tz": "EST"},
        },
    },
    "PHI": {
        "abbreviation": "PHI",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 18, "link": "/api/v1/divisions/18", "name": "Metropolitan"},
        "firstYearOfPlay": "1967",
        "franchise": {
            "franchiseId": 16,
            "link": "/api/v1/franchises/16",
            "teamName": "Flyers",
        },
        "franchiseId": 16,
        "id": 4,
        "link": "/api/v1/teams/4",
        "locationName": "Philadelphia",
        "name": "Philadelphia Flyers",
        "officialSiteUrl": "http://www.philadelphiaflyers.com",
        "shortName": "Philadelphia",
        "teamName": "Flyers",
        "venue": {
            "city": "Philadelphia",
            "link": "/api/v1/venues/null",
            "name": "Wells Fargo Center",
            "timeZone": {"id": "America/New_York", "offset": -5, "tz": "EST"},
        },
    },
    "PHX": {
        "abbreviation": "ARI",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 15, "link": "/api/v1/divisions/15", "name": "Pacific"},
        "firstYearOfPlay": "1979",
        "franchise": {
            "franchiseId": 28,
            "link": "/api/v1/franchises/28",
            "teamName": "Coyotes",
        },
        "franchiseId": 28,
        "id": 53,
        "link": "/api/v1/teams/53",
        "locationName": "Arizona",
        "name": "Arizona Coyotes",
        "officialSiteUrl": "http://www.arizonacoyotes.com",
        "shortName": "Arizona",
        "teamName": "Coyotes",
        "venue": {
            "city": "Glendale",
            "link": "/api/v1/venues/null",
            "name": "Gila River Arena",
            "timeZone": {"id": "America/Phoenix", "offset": -7, "tz": "MST"},
        },
    },
    "PIT": {
        "abbreviation": "PIT",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 18, "link": "/api/v1/divisions/18", "name": "Metropolitan"},
        "firstYearOfPlay": "1967",
        "franchise": {
            "franchiseId": 17,
            "link": "/api/v1/franchises/17",
            "teamName": "Penguins",
        },
        "franchiseId": 17,
        "id": 5,
        "link": "/api/v1/teams/5",
        "locationName": "Pittsburgh",
        "name": "Pittsburgh Penguins",
        "officialSiteUrl": "http://www.pittsburghpenguins.com",
        "shortName": "Pittsburgh",
        "teamName": "Penguins",
        "venue": {
            "city": "Pittsburgh",
            "link": "/api/v1/venues/null",
            "name": "PPG Paints Arena",
            "timeZone": {"id": "America/New_York", "offset": -5, "tz": "EST"},
        },
    },
    "SEA": {
        "id": 55,
        "name": "Seattle Kraken",
        "link": "/api/v1/teams/55",
        "venue": {
            "name": "Climate Pledge Arena",
            "link": "/api/v1/venues/null",
            "city": "Seattle",
            "timeZone": {"id": "America/Los_Angeles", "offset": -7, "tz": "PDT"},
        },
        "abbreviation": "SEA",
        "teamName": "Kraken",
        "locationName": "Seattle",
        "firstYearOfPlay": "2021",
        "division": {
            "id": 15,
            "name": "Pacific",
            "nameShort": "PAC",
            "link": "/api/v1/divisions/15",
            "abbreviation": "P",
        },
        "conference": {"id": 5, "name": "Western", "link": "/api/v1/conferences/5"},
        "franchise": {
            "franchiseId": 39,
            "teamName": "Kraken",
            "link": "/api/v1/franchises/39",
        },
        "shortName": "Seattle",
        "officialSiteUrl": "https://www.nhl.com/seattle",
        "franchiseId": 39,
        "active": True,
    },
    "SJS": {
        "abbreviation": "SJS",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 15, "link": "/api/v1/divisions/15", "name": "Pacific"},
        "firstYearOfPlay": "1990",
        "franchise": {
            "franchiseId": 29,
            "link": "/api/v1/franchises/29",
            "teamName": "Sharks",
        },
        "franchiseId": 29,
        "id": 28,
        "link": "/api/v1/teams/28",
        "locationName": "San Jose",
        "name": "San Jose Sharks",
        "officialSiteUrl": "http://www.sjsharks.com",
        "shortName": "San Jose",
        "teamName": "Sharks",
        "venue": {
            "city": "San Jose",
            "link": "/api/v1/venues/null",
            "name": "SAP Center at San Jose",
            "timeZone": {"id": "America/Los_Angeles", "offset": -8, "tz": "PST"},
        },
    },
    "STL": {
        "abbreviation": "STL",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 16, "link": "/api/v1/divisions/16", "name": "Central"},
        "firstYearOfPlay": "1967",
        "franchise": {
            "franchiseId": 18,
            "link": "/api/v1/franchises/18",
            "teamName": "Blues",
        },
        "franchiseId": 18,
        "id": 19,
        "link": "/api/v1/teams/19",
        "locationName": "St. Louis",
        "name": "St. Louis Blues",
        "officialSiteUrl": "http://www.stlouisblues.com",
        "shortName": "St Louis",
        "teamName": "Blues",
        "venue": {
            "city": "St. Louis",
            "link": "/api/v1/venues/null",
            "name": "Scottrade Center",
            "timeZone": {"id": "America/Chicago", "offset": -6, "tz": "CST"},
        },
    },
    "TBL": {
        "abbreviation": "TBL",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 17, "link": "/api/v1/divisions/17", "name": "Atlantic"},
        "firstYearOfPlay": "1991",
        "franchise": {
            "franchiseId": 31,
            "link": "/api/v1/franchises/31",
            "teamName": "Lightning",
        },
        "franchiseId": 31,
        "id": 14,
        "link": "/api/v1/teams/14",
        "locationName": "Tampa Bay",
        "name": "Tampa Bay Lightning",
        "officialSiteUrl": "http://www.tampabaylightning.com",
        "shortName": "Tampa Bay",
        "teamName": "Lightning",
        "venue": {
            "city": "Tampa",
            "link": "/api/v1/venues/null",
            "name": "Amalie Arena",
            "timeZone": {"id": "America/New_York", "offset": -5, "tz": "EST"},
        },
    },
    "TOR": {
        "abbreviation": "TOR",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 17, "link": "/api/v1/divisions/17", "name": "Atlantic"},
        "firstYearOfPlay": "1917",
        "franchise": {
            "franchiseId": 5,
            "link": "/api/v1/franchises/5",
            "teamName": "Maple Leafs",
        },
        "franchiseId": 5,
        "id": 10,
        "link": "/api/v1/teams/10",
        "locationName": "Toronto",
        "name": "Toronto Maple Leafs",
        "officialSiteUrl": "http://www.mapleleafs.com",
        "shortName": "Toronto",
        "teamName": "Maple Leafs",
        "venue": {
            "city": "Toronto",
            "link": "/api/v1/venues/null",
            "name": "Air Canada Centre",
            "timeZone": {"id": "America/Toronto", "offset": -5, "tz": "EST"},
        },
    },
    "VAN": {
        "abbreviation": "VAN",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 15, "link": "/api/v1/divisions/15", "name": "Pacific"},
        "firstYearOfPlay": "1970",
        "franchise": {
            "franchiseId": 20,
            "link": "/api/v1/franchises/20",
            "teamName": "Canucks",
        },
        "franchiseId": 20,
        "id": 23,
        "link": "/api/v1/teams/23",
        "locationName": "Vancouver",
        "name": "Vancouver Canucks",
        "officialSiteUrl": "http://www.canucks.com",
        "shortName": "Vancouver",
        "teamName": "Canucks",
        "venue": {
            "city": "Vancouver",
            "link": "/api/v1/venues/null",
            "name": "Rogers Arena",
            "timeZone": {"id": "America/Vancouver", "offset": -8, "tz": "PST"},
        },
    },
    "VGK": {
        "abbreviation": "VGK",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 15, "link": "/api/v1/divisions/15", "name": "Pacific"},
        "firstYearOfPlay": "2016",
        "franchise": {
            "franchiseId": 38,
            "link": "/api/v1/franchises/38",
            "teamName": "Golden Knights",
        },
        "franchiseId": 38,
        "id": 54,
        "link": "/api/v1/teams/54",
        "locationName": "Vegas",
        "name": "Vegas Golden Knights",
        "officialSiteUrl": "http://www.vegasgoldenknights.com",
        "shortName": "Vegas",
        "teamName": "Golden Knights",
        "venue": {
            "city": "Las Vegas",
            "link": "/api/v1/venues/null",
            "name": "T-Mobile Arena",
            "timeZone": {"id": "America/Los_Angeles", "offset": -8, "tz": "PST"},
        },
    },
    "WPG": {
        "abbreviation": "WPG",
        "active": True,
        "conference": {"id": 5, "link": "/api/v1/conferences/5", "name": "Western"},
        "division": {"id": 16, "link": "/api/v1/divisions/16", "name": "Central"},
        "firstYearOfPlay": "2011",
        "franchise": {
            "franchiseId": 35,
            "link": "/api/v1/franchises/35",
            "teamName": "Jets",
        },
        "franchiseId": 35,
        "id": 52,
        "link": "/api/v1/teams/52",
        "locationName": "Winnipeg",
        "name": "Winnipeg Jets",
        "officialSiteUrl": "http://winnipegjets.com",
        "shortName": "Winnipeg",
        "teamName": "Jets",
        "venue": {
            "city": "Winnipeg",
            "link": "/api/v1/venues/null",
            "name": "Bell MTS Place",
            "timeZone": {"id": "America/Winnipeg", "offset": -6, "tz": "CST"},
        },
    },
    "WSH": {
        "abbreviation": "WSH",
        "active": True,
        "conference": {"id": 6, "link": "/api/v1/conferences/6", "name": "Eastern"},
        "division": {"id": 18, "link": "/api/v1/divisions/18", "name": "Metropolitan"},
        "firstYearOfPlay": "1974",
        "franchise": {
            "franchiseId": 24,
            "link": "/api/v1/franchises/24",
            "teamName": "Capitals",
        },
        "franchiseId": 24,
        "id": 15,
        "link": "/api/v1/teams/15",
        "locationName": "Washington",
        "name": "Washington Capitals",
        "officialSiteUrl": "http://www.washingtoncapitals.com",
        "shortName": "Washington",
        "teamName": "Capitals",
        "venue": {
            "city": "Washington",
            "link": "/api/v1/venues/null",
            "name": "Capital One Arena",
            "timeZone": {"id": "America/New_York", "offset": -5, "tz": "EST"},
        },
    },
}
