
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-11T11:12:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "262b71291a7f1377c041900d256387820f4e9195",
 "version": "0.7.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
