# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class TransferStatus(str, enum.Enum):
    CREATED = "created"
    SUBMITTED = "submitted"
    FAILED = "failed"

    def visit(
        self,
        created: typing.Callable[[], T_Result],
        submitted: typing.Callable[[], T_Result],
        failed: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is TransferStatus.CREATED:
            return created()
        if self is TransferStatus.SUBMITTED:
            return submitted()
        if self is TransferStatus.FAILED:
            return failed()
