# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.5.19.dev0+g8e57cee.d20230711'
__version_tuple__ = version_tuple = (0, 5, 19, 'dev0', 'g8e57cee.d20230711')
