# Generated by Django 4.1.9 on 2023-06-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_cisco_support_plugin", "0005_ciscodevicesupport_partner_coverage_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciscodevicesupport",
            name="partner_coverage_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
