# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.5.1.dev0+g13366e1.d20230706'
__version_tuple__ = version_tuple = (0, 5, 1, 'dev0', 'g13366e1.d20230706')
