
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-06T20:50:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6ba1f6d177c520767ec20e02f16cc43912ba90a",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
