#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2303-8-gb8c2b08f"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2303
#define NETGEN_VERSION_TWEAK 8
#define NETGEN_VERSION_HASH "gb8c2b08f"
#endif // NETGEN_VERSION_HPP_INCLUDED
