
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-11T19:33:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "13145765d62149d780294cfc9567a781437f8ca8",
 "version": "0.17.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
