# Generated by Django 4.2.3 on 2023-07-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onoffmonitorserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
    ]
