
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-12T11:20:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "feff96d6eeb0daea6d76c0ab03526318d8979b67",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
