# coding: utf-8

"""
    Conekta API

    Conekta sdk  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class DeletedBlacklistRuleResponse(BaseModel):
    """
    DeletedBlacklistRuleResponse
    """
    id: Optional[StrictStr] = Field(None, description="Blacklist rule id")
    field: Optional[StrictStr] = Field(None, description="field used for blacklists rule deleted")
    value: Optional[StrictStr] = Field(None, description="value used for blacklists rule deleted")
    description: Optional[StrictStr] = Field(None, description="use an description for blacklisted rule")
    __properties = ["id", "field", "value", "description"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DeletedBlacklistRuleResponse:
        """Create an instance of DeletedBlacklistRuleResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DeletedBlacklistRuleResponse:
        """Create an instance of DeletedBlacklistRuleResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DeletedBlacklistRuleResponse.parse_obj(obj)

        _obj = DeletedBlacklistRuleResponse.parse_obj({
            "id": obj.get("id"),
            "field": obj.get("field"),
            "value": obj.get("value"),
            "description": obj.get("description")
        })
        return _obj

