
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-07T15:22:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "08326f4217ba412c8d8be3224f9a5ca5855ac3e1",
 "version": "2.10.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
