
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-07T18:26:25+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "07e2d1174aabe2882da7e5c4da419b61679c9e3f",
 "version": "2.11.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
