# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

import os
import sys
import ctypes
import enum
import struct
import contextlib
import datetime
import typing
import platform

# Used for default argument values
DEFAULT = object()


class RustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_int32),
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def alloc(size):
        return rust_call(_UniFFILib.ffi_nostr_sdk_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return rust_call(_UniFFILib.ffi_nostr_sdk_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return rust_call(_UniFFILib.ffi_nostr_sdk_rustbuffer_free, self)

    def __str__(self):
        return "RustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def allocWithBuilder(*args):
        """Context-manger to allocate a buffer using a RustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = RustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consumeWithStream(self):
        """Context-manager to consume a buffer using a RustBufferStream.

        The RustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = RustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError("junk data left in buffer at end of consumeWithStream")
        finally:
            self.free()

    @contextlib.contextmanager
    def readWithStream(self):
        """Context-manager to read a buffer using a RustBufferStream.

        This is like consumeWithStream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `RustBuffer` data.
        """
        s = RustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError("junk data left in buffer at end of readWithStream")

class ForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "ForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class RustBufferStream:
    """
    Helper for structured reading of bytes from a RustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def readI8(self):
        return self._unpack_from(1, ">b")

    def readU8(self):
        return self._unpack_from(1, ">B")

    def readI16(self):
        return self._unpack_from(2, ">h")

    def readU16(self):
        return self._unpack_from(2, ">H")

    def readI32(self):
        return self._unpack_from(4, ">i")

    def readU32(self):
        return self._unpack_from(4, ">I")

    def readI64(self):
        return self._unpack_from(8, ">q")

    def readU64(self):
        return self._unpack_from(8, ">Q")

    def readFloat(self):
        v = self._unpack_from(4, ">f")
        return v

    def readDouble(self):
        return self._unpack_from(8, ">d")

    def readCSizeT(self):
        return self._unpack_from(ctypes.sizeof(ctypes.c_size_t) , "@N")

class RustBufferBuilder:
    """
    Helper for structured writing of bytes into a RustBuffer.
    """

    def __init__(self):
        self.rbuf = RustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, numBytes):
        if self.rbuf.len + numBytes > self.rbuf.capacity:
            self.rbuf = RustBuffer.reserve(self.rbuf, numBytes)
        yield None
        self.rbuf.len += numBytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def writeI8(self, v):
        self._pack_into(1, ">b", v)

    def writeU8(self, v):
        self._pack_into(1, ">B", v)

    def writeI16(self, v):
        self._pack_into(2, ">h", v)

    def writeU16(self, v):
        self._pack_into(2, ">H", v)

    def writeI32(self, v):
        self._pack_into(4, ">i", v)

    def writeU32(self, v):
        self._pack_into(4, ">I", v)

    def writeI64(self, v):
        self._pack_into(8, ">q", v)

    def writeU64(self, v):
        self._pack_into(8, ">Q", v)

    def writeFloat(self, v):
        self._pack_into(4, ">f", v)

    def writeDouble(self, v):
        self._pack_into(8, ">d", v)

    def writeCSizeT(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class RustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", RustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_PANIC = 2

    def __str__(self):
        if self.code == RustCallStatus.CALL_SUCCESS:
            return "RustCallStatus(CALL_SUCCESS)"
        elif self.code == RustCallStatus.CALL_ERROR:
            return "RustCallStatus(CALL_ERROR)"
        elif self.code == RustCallStatus.CALL_PANIC:
            return "RustCallStatus(CALL_PANIC)"
        else:
            return "RustCallStatus(<invalid code>)"

def rust_call(fn, *args):
    # Call a rust function
    return rust_call_with_error(None, fn, *args)

def rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the FfiConverter for the error class that corresponds to the result.
    call_status = RustCallStatus(code=RustCallStatus.CALL_SUCCESS, error_buf=RustBuffer(0, 0, None))

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def rust_call_async(scaffolding_fn, callback_fn, *args):
    # Call the scaffolding function, passing it a callback handler for `AsyncTypes.py` and a pointer
    # to a python Future object.  The async function then awaits the Future.
    uniffi_eventloop = asyncio.get_running_loop()
    uniffi_py_future = uniffi_eventloop.create_future()
    uniffi_call_status = RustCallStatus(code=RustCallStatus.CALL_SUCCESS, error_buf=RustBuffer(0, 0, None))
    scaffolding_fn(*args,
       FfiConverterForeignExecutor._pointer_manager.new_pointer(uniffi_eventloop),
       callback_fn,
       # Note: It's tempting to skip the pointer manager and just use a `py_object` pointing to a
       # local variable like we do in Swift.  However, Python doesn't use cooperative cancellation
       # -- asyncio can cancel a task at anytime.  This means if we use a local variable, the Rust
       # callback could fire with a dangling pointer.
       UniFfiPyFuturePointerManager.new_pointer(uniffi_py_future),
       ctypes.byref(uniffi_call_status),
    )
    uniffi_check_call_status(None, uniffi_call_status)
    return uniffi_py_future

def uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == RustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == RustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == RustCallStatus.CALL_PANIC:
        # When the rust code sees a panic, it tries to construct a RustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = FfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid RustCallStatus code: {}".format(
            call_status.code))

# A function pointer for a callback as defined by UniFFI.
# Rust definition `fn(handle: u64, method: u32, args: RustBuffer, buf_ptr: *mut RustBuffer) -> int`
FOREIGN_CALLBACK_T = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_ulonglong, ctypes.c_ulong, ctypes.POINTER(ctypes.c_char), ctypes.c_int, ctypes.POINTER(RustBuffer))
class UniFfiPointerManagerCPython:
    """
    Manage giving out pointers to Python objects on CPython

    This class is used to generate opaque pointers that reference Python objects to pass to Rust.
    It assumes a CPython platform.  See UniFfiPointerManagerGeneral for the alternative.
    """

    def new_pointer(self, obj):
        """
        Get a pointer for an object as a ctypes.c_size_t instance

        Each call to new_pointer() must be balanced with exactly one call to release_pointer()

        This returns a ctypes.c_size_t.  This is always the same size as a pointer and can be
        interchanged with pointers for FFI function arguments and return values.
        """
        # IncRef the object since we're going to pass a pointer to Rust
        ctypes.pythonapi.Py_IncRef(ctypes.py_object(obj))
        # id() is the object address on CPython
        # (https://docs.python.org/3/library/functions.html#id)
        return id(obj)

    def release_pointer(self, address):
        py_obj = ctypes.cast(address, ctypes.py_object)
        obj = py_obj.value
        ctypes.pythonapi.Py_DecRef(py_obj)
        return obj

    def lookup(self, address):
        return ctypes.cast(address, ctypes.py_object).value

class UniFfiPointerManagerGeneral:
    """
    Manage giving out pointers to Python objects on non-CPython platforms

    This has the same API as UniFfiPointerManagerCPython, but doesn't assume we're running on
    CPython and is slightly slower.

    Instead of using real pointers, it maps integer values to objects and returns the keys as
    c_size_t values.
    """

    def __init__(self):
        self._map = {}
        self._lock = threading.Lock()
        self._current_handle = 0

    def new_pointer(self, obj):
        with self._lock:
            handle = self._current_handle
            self._current_handle += 1
            self._map[handle] = obj
        return handle

    def release_pointer(self, handle):
        with self._lock:
            return self._map.pop(handle)

    def lookup(self, handle):
        with self._lock:
            return self._map[handle]

# Pick an pointer manager implementation based on the platform
if platform.python_implementation() == 'CPython':
    UniFfiPointerManager = UniFfiPointerManagerCPython  # type: ignore
else:
    UniFfiPointerManager = UniFfiPointerManagerGeneral  # type: ignore
# Types conforming to `FfiConverterPrimitive` pass themselves directly over the FFI.
class FfiConverterPrimitive:
    @classmethod
    def check(cls, value):
        return value

    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return cls.lowerUnchecked(cls.check(value))

    @classmethod
    def lowerUnchecked(cls, value):
        return value

    @classmethod
    def write(cls, value, buf):
        cls.writeUnchecked(cls.check(value), buf)

class FfiConverterPrimitiveInt(FfiConverterPrimitive):
    @classmethod
    def check(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))
        return super().check(value)

class FfiConverterPrimitiveFloat(FfiConverterPrimitive):
    @classmethod
    def check(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))
        return super().check(value)

# Helper class for wrapper types that will always go through a RustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class FfiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consumeWithStream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with RustBuffer.allocWithBuilder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code,
# and the FFI Function declarations in a com.sun.jna.Library.
# Define some ctypes FFI types that we use in the library

"""
ctypes type for the foreign executor callback.  This is a built-in interface for scheduling
tasks

Args:
  executor: opaque c_size_t value representing the eventloop
  delay: delay in ms
  task: function pointer to the task callback
  task_data: void pointer to the task callback data

Normally we should call task(task_data) after the detail.
However, when task is NULL this indicates that Rust has dropped the ForeignExecutor and we should
decrease the EventLoop refcount.
"""
UNIFFI_FOREIGN_EXECUTOR_CALLBACK_T = ctypes.CFUNCTYPE(None, ctypes.c_size_t, ctypes.c_uint32, ctypes.c_void_p, ctypes.c_void_p)

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p)

def uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_size_t, return_type, RustCallStatus)

from pathlib import Path

def loadIndirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("nostr_sdk_ffi")
    path = str(Path(__file__).parent / libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 22
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_nostr_sdk_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def uniffi_check_api_checksums(lib):
    if lib.uniffi_nostr_sdk_checksum_func_init_logger() != 57668:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_func_timestamp() != 13516:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_keys_public_key() != 8008:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_keys_public_key_bech32() != 5014:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_keys_secret_key() != 20726:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_keys_secret_key_bech32() != 9035:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_filter_id() != 58951:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_filter_ids() != 43459:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_filter_kind() != 32792:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_filter_event() != 41110:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_filter_pubkey() != 885:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_filter_since() != 29494:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_filter_until() != 35046:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_filter_authors() != 37738:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_event_pubkey() != 21056:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_event_kind() != 9991:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_event_content() != 61289:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_event_verify() != 42880:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_event_as_json() != 26774:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_eventbuilder_to_event() != 47288:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_eventbuilder_to_pow_event() != 49016:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_contact_alias() != 7484:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_contact_public_key() != 9945:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_contact_relay_url() != 5572:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_accountmetadata_name() != 32146:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_accountmetadata_display_name() != 31496:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_accountmetadata_about() != 245:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_accountmetadata_picture() != 42395:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_accountmetadata_nip05() != 36375:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_client_add_relay() != 46021:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_client_connect_relay() != 44731:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_client_connect() != 1786:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_client_subscribe() != 59977:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_client_send_event() != 62429:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_method_client_handle_notifications() != 6806:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_keys_new() != 6492:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_keys_from_public_key() != 23586:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_keys_from_bech32_public_key() != 13442:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_keys_from_bech32() != 24856:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_keys_generate() != 7127:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_keys_from_mnemonic() != 55257:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_filter_new() != 59121:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_event_from_json() != 40059:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new() != 5433:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_set_metadata() != 50751:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_add_recommended_relay() != 20155:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_text_note() != 32743:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_long_form_text_note() != 27538:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_repost() != 62601:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_set_contact_list() != 55954:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_encrypted_direct_msg() != 48397:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_delete() != 37795:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_reaction() != 15533:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_channel() != 14798:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_set_channel_metadata() != 5534:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_channel_msg() != 32541:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_hide_channel_msg() != 20684:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_mute_channel_user() != 28542:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_auth() != 682:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_contact_new() != 20096:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_accountmetadata_new() != 65302:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_nostr_sdk_checksum_constructor_client_new() != 40232:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniFFILib = loadIndirect()
_UniFFILib.uniffi_nostr_sdk_fn_free_keys.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_free_keys.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_new.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_new.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_from_public_key.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_from_public_key.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_from_bech32_public_key.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_from_bech32_public_key.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_from_bech32.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_from_bech32.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_generate.argtypes = (
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_generate.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_from_mnemonic.argtypes = (
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_from_mnemonic.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_keys_public_key.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_keys_public_key.restype = RustBuffer
_UniFFILib.uniffi_nostr_sdk_fn_method_keys_public_key_bech32.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_keys_public_key_bech32.restype = RustBuffer
_UniFFILib.uniffi_nostr_sdk_fn_method_keys_secret_key.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_keys_secret_key.restype = RustBuffer
_UniFFILib.uniffi_nostr_sdk_fn_method_keys_secret_key_bech32.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_keys_secret_key_bech32.restype = RustBuffer
_UniFFILib.uniffi_nostr_sdk_fn_free_filter.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_free_filter.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_constructor_filter_new.argtypes = (
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_filter_new.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_id.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_id.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_ids.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_ids.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_kind.argtypes = (
    ctypes.c_void_p,
    ctypes.c_uint64,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_kind.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_event.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_event.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_pubkey.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_pubkey.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_since.argtypes = (
    ctypes.c_void_p,
    ctypes.c_uint64,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_since.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_until.argtypes = (
    ctypes.c_void_p,
    ctypes.c_uint64,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_until.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_authors.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_filter_authors.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_free_event.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_free_event.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_constructor_event_from_json.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_event_from_json.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_event_pubkey.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_event_pubkey.restype = RustBuffer
_UniFFILib.uniffi_nostr_sdk_fn_method_event_kind.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_event_kind.restype = ctypes.c_uint64
_UniFFILib.uniffi_nostr_sdk_fn_method_event_content.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_event_content.restype = RustBuffer
_UniFFILib.uniffi_nostr_sdk_fn_method_event_verify.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_event_verify.restype = ctypes.c_int8
_UniFFILib.uniffi_nostr_sdk_fn_method_event_as_json.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_event_as_json.restype = RustBuffer
_UniFFILib.uniffi_nostr_sdk_fn_free_eventbuilder.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_free_eventbuilder.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new.argtypes = (
    ctypes.c_uint64,
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_set_metadata.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_set_metadata.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_add_recommended_relay.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_add_recommended_relay.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_text_note.argtypes = (
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_text_note.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_long_form_text_note.argtypes = (
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_long_form_text_note.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_repost.argtypes = (
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_repost.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_set_contact_list.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_set_contact_list.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_encrypted_direct_msg.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_encrypted_direct_msg.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_delete.argtypes = (
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_delete.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_reaction.argtypes = (
    RustBuffer,
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_reaction.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_channel.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_channel.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_set_channel_metadata.argtypes = (
    RustBuffer,
    RustBuffer,
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_set_channel_metadata.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_channel_msg.argtypes = (
    RustBuffer,
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_channel_msg.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_hide_channel_msg.argtypes = (
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_hide_channel_msg.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_mute_channel_user.argtypes = (
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_mute_channel_user.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_auth.argtypes = (
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_auth.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_eventbuilder_to_event.argtypes = (
    ctypes.c_void_p,
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_eventbuilder_to_event.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_eventbuilder_to_pow_event.argtypes = (
    ctypes.c_void_p,
    ctypes.c_void_p,
    ctypes.c_uint8,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_eventbuilder_to_pow_event.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_free_contact.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_free_contact.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_constructor_contact_new.argtypes = (
    RustBuffer,
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_contact_new.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_contact_alias.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_contact_alias.restype = RustBuffer
_UniFFILib.uniffi_nostr_sdk_fn_method_contact_public_key.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_contact_public_key.restype = RustBuffer
_UniFFILib.uniffi_nostr_sdk_fn_method_contact_relay_url.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_contact_relay_url.restype = RustBuffer
_UniFFILib.uniffi_nostr_sdk_fn_free_accountmetadata.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_free_accountmetadata.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_constructor_accountmetadata_new.argtypes = (
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_accountmetadata_new.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_name.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_name.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_display_name.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_display_name.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_about.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_about.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_picture.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_picture.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_nip05.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_nip05.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_free_client.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_free_client.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_constructor_client_new.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_constructor_client_new.restype = ctypes.c_void_p
_UniFFILib.uniffi_nostr_sdk_fn_method_client_add_relay.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_client_add_relay.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_method_client_connect_relay.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_client_connect_relay.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_method_client_connect.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_client_connect.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_method_client_subscribe.argtypes = (
    ctypes.c_void_p,
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_client_subscribe.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_method_client_send_event.argtypes = (
    ctypes.c_void_p,
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_client_send_event.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_method_client_handle_notifications.argtypes = (
    ctypes.c_void_p,
    ctypes.c_uint64,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_method_client_handle_notifications.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_init_callback_handlenotification.argtypes = (
    FOREIGN_CALLBACK_T,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_init_callback_handlenotification.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_func_init_logger.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_func_init_logger.restype = None
_UniFFILib.uniffi_nostr_sdk_fn_func_timestamp.argtypes = (
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_nostr_sdk_fn_func_timestamp.restype = ctypes.c_uint64
_UniFFILib.ffi_nostr_sdk_rustbuffer_alloc.argtypes = (
    ctypes.c_int32,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.ffi_nostr_sdk_rustbuffer_alloc.restype = RustBuffer
_UniFFILib.ffi_nostr_sdk_rustbuffer_from_bytes.argtypes = (
    ForeignBytes,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.ffi_nostr_sdk_rustbuffer_from_bytes.restype = RustBuffer
_UniFFILib.ffi_nostr_sdk_rustbuffer_free.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.ffi_nostr_sdk_rustbuffer_free.restype = None
_UniFFILib.ffi_nostr_sdk_rustbuffer_reserve.argtypes = (
    RustBuffer,
    ctypes.c_int32,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.ffi_nostr_sdk_rustbuffer_reserve.restype = RustBuffer
_UniFFILib.uniffi_nostr_sdk_checksum_func_init_logger.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_func_init_logger.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_func_timestamp.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_func_timestamp.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_keys_public_key.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_keys_public_key.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_keys_public_key_bech32.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_keys_public_key_bech32.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_keys_secret_key.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_keys_secret_key.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_keys_secret_key_bech32.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_keys_secret_key_bech32.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_id.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_id.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_ids.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_ids.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_kind.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_kind.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_event.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_event.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_pubkey.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_pubkey.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_since.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_since.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_until.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_until.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_authors.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_filter_authors.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_event_pubkey.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_event_pubkey.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_event_kind.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_event_kind.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_event_content.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_event_content.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_event_verify.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_event_verify.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_event_as_json.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_event_as_json.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_eventbuilder_to_event.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_eventbuilder_to_event.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_eventbuilder_to_pow_event.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_eventbuilder_to_pow_event.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_contact_alias.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_contact_alias.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_contact_public_key.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_contact_public_key.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_contact_relay_url.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_contact_relay_url.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_accountmetadata_name.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_accountmetadata_name.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_accountmetadata_display_name.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_accountmetadata_display_name.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_accountmetadata_about.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_accountmetadata_about.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_accountmetadata_picture.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_accountmetadata_picture.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_accountmetadata_nip05.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_accountmetadata_nip05.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_client_add_relay.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_client_add_relay.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_client_connect_relay.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_client_connect_relay.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_client_connect.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_client_connect.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_client_subscribe.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_client_subscribe.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_client_send_event.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_client_send_event.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_method_client_handle_notifications.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_method_client_handle_notifications.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_keys_new.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_keys_new.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_keys_from_public_key.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_keys_from_public_key.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_keys_from_bech32_public_key.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_keys_from_bech32_public_key.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_keys_from_bech32.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_keys_from_bech32.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_keys_generate.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_keys_generate.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_keys_from_mnemonic.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_keys_from_mnemonic.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_filter_new.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_filter_new.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_event_from_json.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_event_from_json.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_set_metadata.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_set_metadata.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_add_recommended_relay.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_add_recommended_relay.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_text_note.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_text_note.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_long_form_text_note.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_long_form_text_note.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_repost.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_repost.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_set_contact_list.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_set_contact_list.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_encrypted_direct_msg.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_encrypted_direct_msg.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_delete.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_delete.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_reaction.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_reaction.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_channel.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_channel.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_set_channel_metadata.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_set_channel_metadata.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_channel_msg.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_new_channel_msg.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_hide_channel_msg.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_hide_channel_msg.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_mute_channel_user.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_mute_channel_user.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_auth.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_eventbuilder_auth.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_contact_new.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_contact_new.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_accountmetadata_new.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_accountmetadata_new.restype = ctypes.c_uint16
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_client_new.argtypes = (
)
_UniFFILib.uniffi_nostr_sdk_checksum_constructor_client_new.restype = ctypes.c_uint16
_UniFFILib.ffi_nostr_sdk_uniffi_contract_version.argtypes = (
)
_UniFFILib.ffi_nostr_sdk_uniffi_contract_version.restype = ctypes.c_uint32
uniffi_check_contract_api_version(_UniFFILib)
uniffi_check_api_checksums(_UniFFILib)

# Public interface members begin here.


class FfiConverterUInt8(FfiConverterPrimitiveInt):
    CLASS_NAME = "u8"
    VALUE_MIN = 0
    VALUE_MAX = 2**8

    @staticmethod
    def read(buf):
        return buf.readU8()

    @staticmethod
    def writeUnchecked(value, buf):
        buf.writeU8(value)

class FfiConverterUInt64(FfiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.readU64()

    @staticmethod
    def writeUnchecked(value, buf):
        buf.writeU64(value)

class FfiConverterBool(FfiConverterPrimitive):
    @classmethod
    def check(cls, value):
        return not not value

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.readU8())

    @classmethod
    def writeUnchecked(cls, value, buf):
        buf.writeU8(value)

    @staticmethod
    def lift(value):
        return value != 0

class FfiConverterString:
    @staticmethod
    def check(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.readI32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8Bytes = buf.read(size)
        return utf8Bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        value = FfiConverterString.check(value)
        utf8Bytes = value.encode("utf-8")
        buf.writeI32(len(utf8Bytes))
        buf.write(utf8Bytes)

    @staticmethod
    def lift(buf):
        with buf.consumeWithStream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        value = FfiConverterString.check(value)
        with RustBuffer.allocWithBuilder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()



class AccountMetadata:
    _pointer: ctypes.c_void_p
    def __init__(self, ):
        self._pointer = rust_call(_UniFFILib.uniffi_nostr_sdk_fn_constructor_accountmetadata_new,)

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_free_accountmetadata, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def name(self, name: "str") -> "AccountMetadata":
        
        return FfiConverterTypeAccountMetadata.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_name,self._pointer,
        FfiConverterString.lower(name))
        )






    def display_name(self, display_name: "str") -> "AccountMetadata":
        
        return FfiConverterTypeAccountMetadata.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_display_name,self._pointer,
        FfiConverterString.lower(display_name))
        )






    def about(self, about: "str") -> "AccountMetadata":
        
        return FfiConverterTypeAccountMetadata.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_about,self._pointer,
        FfiConverterString.lower(about))
        )






    def picture(self, picture: "str") -> "AccountMetadata":
        
        return FfiConverterTypeAccountMetadata.lift(
            rust_call_with_error(
    FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_picture,self._pointer,
        FfiConverterString.lower(picture))
        )






    def nip05(self, nip05: "str") -> "AccountMetadata":
        
        return FfiConverterTypeAccountMetadata.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_accountmetadata_nip05,self._pointer,
        FfiConverterString.lower(nip05))
        )






class FfiConverterTypeAccountMetadata:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, AccountMetadata):
            raise TypeError("Expected AccountMetadata instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return AccountMetadata._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer



class Client:
    _pointer: ctypes.c_void_p
    def __init__(self, keys: "Keys"):
        
        self._pointer = rust_call(_UniFFILib.uniffi_nostr_sdk_fn_constructor_client_new,
        FfiConverterTypeKeys.lower(keys))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_free_client, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def add_relay(self, url: "str",proxy: "typing.Union[object, typing.Optional[str]]" = DEFAULT):
        
        if proxy is DEFAULT:
            proxy = None
        
        rust_call_with_error(
    FfiConverterTypeNostrSdkError,_UniFFILib.uniffi_nostr_sdk_fn_method_client_add_relay,self._pointer,
        FfiConverterString.lower(url),
        FfiConverterOptionalString.lower(proxy))







    def connect_relay(self, url: "str"):
        
        rust_call_with_error(
    FfiConverterTypeNostrSdkError,_UniFFILib.uniffi_nostr_sdk_fn_method_client_connect_relay,self._pointer,
        FfiConverterString.lower(url))







    def connect(self, ):
        rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_client_connect,self._pointer,)







    def subscribe(self, filters: "typing.List[Filter]"):
        
        rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_client_subscribe,self._pointer,
        FfiConverterSequenceTypeFilter.lower(filters))







    def send_event(self, event: "Event"):
        
        rust_call_with_error(
    FfiConverterTypeNostrSdkError,_UniFFILib.uniffi_nostr_sdk_fn_method_client_send_event,self._pointer,
        FfiConverterTypeEvent.lower(event))







    def handle_notifications(self, handler: "HandleNotification"):
        
        rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_client_handle_notifications,self._pointer,
        FfiConverterCallbackInterfaceHandleNotification.lower(handler))







class FfiConverterTypeClient:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, Client):
            raise TypeError("Expected Client instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return Client._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer



class Contact:
    _pointer: ctypes.c_void_p
    def __init__(self, pk: "str",relay_url: "typing.Union[object, typing.Optional[str]]" = DEFAULT,alias: "typing.Union[object, typing.Optional[str]]" = DEFAULT):
        
        if relay_url is DEFAULT:
            relay_url = None
        
        if alias is DEFAULT:
            alias = None
        
        self._pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_contact_new,
        FfiConverterString.lower(pk),
        FfiConverterOptionalString.lower(relay_url),
        FfiConverterOptionalString.lower(alias))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_free_contact, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def alias(self, ) -> "typing.Optional[str]":
        return FfiConverterOptionalString.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_contact_alias,self._pointer,)
        )






    def public_key(self, ) -> "str":
        return FfiConverterString.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_contact_public_key,self._pointer,)
        )






    def relay_url(self, ) -> "typing.Optional[str]":
        return FfiConverterOptionalString.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_contact_relay_url,self._pointer,)
        )






class FfiConverterTypeContact:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, Contact):
            raise TypeError("Expected Contact instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return Contact._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer



class Event:
    _pointer: ctypes.c_void_p

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_free_event, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst

    @classmethod
    def from_json(cls, json: "str"):
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_event_from_json,
        FfiConverterString.lower(json))
        return cls._make_instance_(pointer)



    def pubkey(self, ) -> "str":
        return FfiConverterString.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_event_pubkey,self._pointer,)
        )






    def kind(self, ) -> "int":
        return FfiConverterUInt64.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_event_kind,self._pointer,)
        )






    def content(self, ) -> "str":
        return FfiConverterString.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_event_content,self._pointer,)
        )






    def verify(self, ) -> "bool":
        return FfiConverterBool.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_event_verify,self._pointer,)
        )






    def as_json(self, ) -> "str":
        return FfiConverterString.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_event_as_json,self._pointer,)
        )






class FfiConverterTypeEvent:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, Event):
            raise TypeError("Expected Event instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return Event._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer



class EventBuilder:
    _pointer: ctypes.c_void_p
    def __init__(self, kind: "int",content: "str",tags: "typing.List[typing.List[str]]"):
        
        
        
        self._pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new,
        FfiConverterUInt64.lower(kind),
        FfiConverterString.lower(content),
        FfiConverterSequenceSequenceString.lower(tags))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_free_eventbuilder, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst

    @classmethod
    def set_metadata(cls, metadata: "AccountMetadata"):
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call(_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_set_metadata,
        FfiConverterTypeAccountMetadata.lower(metadata))
        return cls._make_instance_(pointer)


    @classmethod
    def add_recommended_relay(cls, url: "str"):
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_add_recommended_relay,
        FfiConverterString.lower(url))
        return cls._make_instance_(pointer)


    @classmethod
    def new_text_note(cls, content: "str",tags: "typing.List[typing.List[str]]"):
        
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_text_note,
        FfiConverterString.lower(content),
        FfiConverterSequenceSequenceString.lower(tags))
        return cls._make_instance_(pointer)


    @classmethod
    def long_form_text_note(cls, content: "str",tags: "typing.List[typing.List[str]]"):
        
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_long_form_text_note,
        FfiConverterString.lower(content),
        FfiConverterSequenceSequenceString.lower(tags))
        return cls._make_instance_(pointer)


    @classmethod
    def repost(cls, event_id: "str",public_key: "str"):
        
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_repost,
        FfiConverterString.lower(event_id),
        FfiConverterString.lower(public_key))
        return cls._make_instance_(pointer)


    @classmethod
    def set_contact_list(cls, list: "typing.List[Contact]"):
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call(_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_set_contact_list,
        FfiConverterSequenceTypeContact.lower(list))
        return cls._make_instance_(pointer)


    @classmethod
    def new_encrypted_direct_msg(cls, sender_keys: "Keys",receiver_pubkey: "str",content: "str"):
        
        
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_encrypted_direct_msg,
        FfiConverterTypeKeys.lower(sender_keys),
        FfiConverterString.lower(receiver_pubkey),
        FfiConverterString.lower(content))
        return cls._make_instance_(pointer)


    @classmethod
    def delete(cls, ids: "typing.List[str]",reason: "typing.Union[object, typing.Optional[str]]" = DEFAULT):
        
        if reason is DEFAULT:
            reason = None
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_delete,
        FfiConverterSequenceString.lower(ids),
        FfiConverterOptionalString.lower(reason))
        return cls._make_instance_(pointer)


    @classmethod
    def new_reaction(cls, event_id: "str",public_key: "str",content: "str"):
        
        
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_reaction,
        FfiConverterString.lower(event_id),
        FfiConverterString.lower(public_key),
        FfiConverterString.lower(content))
        return cls._make_instance_(pointer)


    @classmethod
    def new_channel(cls, metadata: "AccountMetadata"):
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call(_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_channel,
        FfiConverterTypeAccountMetadata.lower(metadata))
        return cls._make_instance_(pointer)


    @classmethod
    def set_channel_metadata(cls, channel_id: "str",relay_url: "typing.Optional[str]",metadata: "AccountMetadata"):
        
        
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_set_channel_metadata,
        FfiConverterString.lower(channel_id),
        FfiConverterOptionalString.lower(relay_url),
        FfiConverterTypeAccountMetadata.lower(metadata))
        return cls._make_instance_(pointer)


    @classmethod
    def new_channel_msg(cls, channel_id: "str",relay_url: "str",content: "str"):
        
        
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_new_channel_msg,
        FfiConverterString.lower(channel_id),
        FfiConverterString.lower(relay_url),
        FfiConverterString.lower(content))
        return cls._make_instance_(pointer)


    @classmethod
    def hide_channel_msg(cls, message_id: "str",reason: "typing.Optional[str]"):
        
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_hide_channel_msg,
        FfiConverterString.lower(message_id),
        FfiConverterOptionalString.lower(reason))
        return cls._make_instance_(pointer)


    @classmethod
    def mute_channel_user(cls, public_key: "str",reason: "typing.Optional[str]"):
        
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_mute_channel_user,
        FfiConverterString.lower(public_key),
        FfiConverterOptionalString.lower(reason))
        return cls._make_instance_(pointer)


    @classmethod
    def auth(cls, challenge: "str",relay_url: "str"):
        
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_eventbuilder_auth,
        FfiConverterString.lower(challenge),
        FfiConverterString.lower(relay_url))
        return cls._make_instance_(pointer)



    def to_event(self, keys: "Keys") -> "Event":
        
        return FfiConverterTypeEvent.lift(
            rust_call_with_error(
    FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_method_eventbuilder_to_event,self._pointer,
        FfiConverterTypeKeys.lower(keys))
        )






    def to_pow_event(self, keys: "Keys",difficulty: "int") -> "Event":
        
        
        return FfiConverterTypeEvent.lift(
            rust_call_with_error(
    FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_method_eventbuilder_to_pow_event,self._pointer,
        FfiConverterTypeKeys.lower(keys),
        FfiConverterUInt8.lower(difficulty))
        )






class FfiConverterTypeEventBuilder:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, EventBuilder):
            raise TypeError("Expected EventBuilder instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return EventBuilder._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer



class Filter:
    _pointer: ctypes.c_void_p
    def __init__(self, ):
        self._pointer = rust_call(_UniFFILib.uniffi_nostr_sdk_fn_constructor_filter_new,)

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_free_filter, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def id(self, id: "str") -> "Filter":
        
        return FfiConverterTypeFilter.lift(
            rust_call_with_error(
    FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_method_filter_id,self._pointer,
        FfiConverterString.lower(id))
        )






    def ids(self, ids: "typing.List[str]") -> "Filter":
        
        return FfiConverterTypeFilter.lift(
            rust_call_with_error(
    FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_method_filter_ids,self._pointer,
        FfiConverterSequenceString.lower(ids))
        )






    def kind(self, kind: "int") -> "Filter":
        
        return FfiConverterTypeFilter.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_filter_kind,self._pointer,
        FfiConverterUInt64.lower(kind))
        )






    def event(self, event_id: "str") -> "Filter":
        
        return FfiConverterTypeFilter.lift(
            rust_call_with_error(
    FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_method_filter_event,self._pointer,
        FfiConverterString.lower(event_id))
        )






    def pubkey(self, pubkey: "str") -> "Filter":
        
        return FfiConverterTypeFilter.lift(
            rust_call_with_error(
    FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_method_filter_pubkey,self._pointer,
        FfiConverterString.lower(pubkey))
        )






    def since(self, timestamp: "int") -> "Filter":
        
        return FfiConverterTypeFilter.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_filter_since,self._pointer,
        FfiConverterUInt64.lower(timestamp))
        )






    def until(self, timestamp: "int") -> "Filter":
        
        return FfiConverterTypeFilter.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_filter_until,self._pointer,
        FfiConverterUInt64.lower(timestamp))
        )






    def authors(self, authors: "typing.List[str]") -> "Filter":
        
        return FfiConverterTypeFilter.lift(
            rust_call_with_error(
    FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_method_filter_authors,self._pointer,
        FfiConverterSequenceString.lower(authors))
        )






class FfiConverterTypeFilter:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, Filter):
            raise TypeError("Expected Filter instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return Filter._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer



class Keys:
    _pointer: ctypes.c_void_p
    def __init__(self, sk: "str"):
        
        self._pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_new,
        FfiConverterString.lower(sk))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_free_keys, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst

    @classmethod
    def from_public_key(cls, pk: "str"):
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_from_public_key,
        FfiConverterString.lower(pk))
        return cls._make_instance_(pointer)


    @classmethod
    def from_bech32_public_key(cls, pk: "str"):
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_from_bech32_public_key,
        FfiConverterString.lower(pk))
        return cls._make_instance_(pointer)


    @classmethod
    def from_bech32(cls, sk: "str"):
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_from_bech32,
        FfiConverterString.lower(sk))
        return cls._make_instance_(pointer)


    @classmethod
    def generate(cls, ):
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call(_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_generate,)
        return cls._make_instance_(pointer)


    @classmethod
    def from_mnemonic(cls, mnemonic: "str",passphrase: "typing.Union[object, typing.Optional[str]]" = DEFAULT):
        
        if passphrase is DEFAULT:
            passphrase = None
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call_with_error(FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_constructor_keys_from_mnemonic,
        FfiConverterString.lower(mnemonic),
        FfiConverterOptionalString.lower(passphrase))
        return cls._make_instance_(pointer)



    def public_key(self, ) -> "str":
        return FfiConverterString.lift(
            rust_call(_UniFFILib.uniffi_nostr_sdk_fn_method_keys_public_key,self._pointer,)
        )






    def public_key_bech32(self, ) -> "str":
        return FfiConverterString.lift(
            rust_call_with_error(
    FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_method_keys_public_key_bech32,self._pointer,)
        )






    def secret_key(self, ) -> "str":
        return FfiConverterString.lift(
            rust_call_with_error(
    FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_method_keys_secret_key,self._pointer,)
        )






    def secret_key_bech32(self, ) -> "str":
        return FfiConverterString.lift(
            rust_call_with_error(
    FfiConverterTypeNostrError,_UniFFILib.uniffi_nostr_sdk_fn_method_keys_secret_key_bech32,self._pointer,)
        )






class FfiConverterTypeKeys:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, Keys):
            raise TypeError("Expected Keys instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return Keys._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer


# NostrError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class NostrError(Exception):
    pass

UniFFITempNostrError = NostrError

class NostrError:  # type: ignore
    class Generic(UniFFITempNostrError):
        def __init__(self, err):
            super().__init__(", ".join([
                "err={!r}".format(err),
            ]))
            self.err = err
        def __repr__(self):
            return "NostrError.Generic({})".format(str(self))
    UniFFITempNostrError.Generic = Generic  # type: ignore

NostrError = UniFFITempNostrError  # type: ignore
del UniFFITempNostrError


class FfiConverterTypeNostrError(FfiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.readI32()
        if variant == 1:
            return NostrError.Generic(
                err=FfiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def write(value, buf):
        if isinstance(value, NostrError.Generic):
            buf.writeI32(1)
            FfiConverterString.write(value.err, buf)


# NostrSdkError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class NostrSdkError(Exception):
    pass

UniFFITempNostrSdkError = NostrSdkError

class NostrSdkError:  # type: ignore
    class Generic(UniFFITempNostrSdkError):
        def __init__(self, err):
            super().__init__(", ".join([
                "err={!r}".format(err),
            ]))
            self.err = err
        def __repr__(self):
            return "NostrSdkError.Generic({})".format(str(self))
    UniFFITempNostrSdkError.Generic = Generic  # type: ignore

NostrSdkError = UniFFITempNostrSdkError  # type: ignore
del UniFFITempNostrSdkError


class FfiConverterTypeNostrSdkError(FfiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.readI32()
        if variant == 1:
            return NostrSdkError.Generic(
                err=FfiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def write(value, buf):
        if isinstance(value, NostrSdkError.Generic):
            buf.writeI32(1)
            FfiConverterString.write(value.err, buf)



import threading

class ConcurrentHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._left_map = {}  # type: Dict[Handle, Any]
        self._right_map = {}  # type: Dict[Any, Handle]

        self._lock = threading.Lock()
        self._current_handle = 0
        self._stride = 1


    def insert(self, obj):
        with self._lock:
            if obj in self._right_map:
                return self._right_map[obj]
            else:
                handle = self._current_handle
                self._current_handle += self._stride
                self._left_map[handle] = obj
                self._right_map[obj] = handle
                return handle

    def get(self, handle):
        with self._lock:
            return self._left_map.get(handle)

    def remove(self, handle):
        with self._lock:
            if handle in self._left_map:
                obj = self._left_map.pop(handle)
                del self._right_map[obj]
                return obj

# Magic number for the Rust proxy to call using the same mechanism as every other method,
# to free the callback once it's dropped by Rust.
IDX_CALLBACK_FREE = 0
# Return codes for callback calls
UNIFFI_CALLBACK_SUCCESS = 0
UNIFFI_CALLBACK_ERROR = 1
UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

class FfiConverterCallbackInterface:
    _handle_map = ConcurrentHandleMap()

    def __init__(self, cb):
        self._foreign_callback = cb

    def drop(self, handle):
        self.__class__._handle_map.remove(handle)

    @classmethod
    def lift(cls, handle):
        obj = cls._handle_map.get(handle)
        if not obj:
            raise InternalError("The object in the handle map has been dropped already")

        return obj

    @classmethod
    def read(cls, buf):
        handle = buf.readU64()
        cls.lift(handle)

    @classmethod
    def lower(cls, cb):
        handle = cls._handle_map.insert(cb)
        return handle

    @classmethod
    def write(cls, cb, buf):
        buf.writeU64(cls.lower(cb))

# Declaration and FfiConverters for HandleNotification Callback Interface

class HandleNotification:
    def handle(self, event: "Event"):
        raise NotImplementedError

    

def py_foreignCallbackCallbackInterfaceHandleNotification(handle, method, args_data, args_len, buf_ptr):
    
    def invoke_handle(python_callback, args_stream, buf_ptr):
        def makeCall():return python_callback.handle(
                FfiConverterTypeEvent.read(args_stream)
                )

        def makeCallAndHandleReturn():
            makeCall()
            return UNIFFI_CALLBACK_SUCCESS
        return makeCallAndHandleReturn()

    

    cb = FfiConverterCallbackInterfaceHandleNotification.lift(handle)
    if not cb:
        raise InternalError("No callback in handlemap; this is a Uniffi bug")

    if method == IDX_CALLBACK_FREE:
        FfiConverterCallbackInterfaceHandleNotification.drop(handle)
        # Successfull return
        # See docs of ForeignCallback in `uniffi_core/src/ffi/foreigncallbacks.rs`
        return UNIFFI_CALLBACK_SUCCESS

    if method == 1:
        # Call the method and handle any errors
        # See docs of ForeignCallback in `uniffi_core/src/ffi/foreigncallbacks.rs` for details
        try:
            return invoke_handle(cb, RustBufferStream(args_data, args_len), buf_ptr)
        except BaseException as e:
            # Catch unexpected errors
            try:
                # Try to serialize the exception into a String
                buf_ptr[0] = FfiConverterString.lower(repr(e))
            except:
                # If that fails, just give up
                pass
            return UNIFFI_CALLBACK_UNEXPECTED_ERROR
    

    # This should never happen, because an out of bounds method index won't
    # ever be used. Once we can catch errors, we should return an InternalException.
    # https://github.com/mozilla/uniffi-rs/issues/351

    # An unexpected error happened.
    # See docs of ForeignCallback in `uniffi_core/src/ffi/foreigncallbacks.rs`
    return UNIFFI_CALLBACK_UNEXPECTED_ERROR

# We need to keep this function reference alive:
# if they get GC'd while in use then UniFFI internals could attempt to call a function
# that is in freed memory.
# That would be...uh...bad. Yeah, that's the word. Bad.
foreignCallbackCallbackInterfaceHandleNotification = FOREIGN_CALLBACK_T(py_foreignCallbackCallbackInterfaceHandleNotification)
rust_call(lambda err: _UniFFILib.uniffi_nostr_sdk_fn_init_callback_handlenotification(foreignCallbackCallbackInterfaceHandleNotification, err))

# The FfiConverter which transforms the Callbacks in to Handles to pass to Rust.
FfiConverterCallbackInterfaceHandleNotification = FfiConverterCallbackInterface(foreignCallbackCallbackInterfaceHandleNotification)



class FfiConverterOptionalString(FfiConverterRustBuffer):
    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.writeU8(0)
            return

        buf.writeU8(1)
        FfiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.readU8()
        if flag == 0:
            return None
        elif flag == 1:
            return FfiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class FfiConverterSequenceString(FfiConverterRustBuffer):
    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.writeI32(items)
        for item in value:
            FfiConverterString.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.readI32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            FfiConverterString.read(buf) for i in range(count)
        ]



class FfiConverterSequenceTypeContact(FfiConverterRustBuffer):
    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.writeI32(items)
        for item in value:
            FfiConverterTypeContact.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.readI32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            FfiConverterTypeContact.read(buf) for i in range(count)
        ]



class FfiConverterSequenceTypeFilter(FfiConverterRustBuffer):
    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.writeI32(items)
        for item in value:
            FfiConverterTypeFilter.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.readI32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            FfiConverterTypeFilter.read(buf) for i in range(count)
        ]



class FfiConverterSequenceSequenceString(FfiConverterRustBuffer):
    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.writeI32(items)
        for item in value:
            FfiConverterSequenceString.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.readI32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            FfiConverterSequenceString.read(buf) for i in range(count)
        ]

def init_logger(level: "typing.Union[object, typing.Optional[str]]" = DEFAULT):
    if level is DEFAULT:
        level = None
    
    rust_call(_UniFFILib.uniffi_nostr_sdk_fn_func_init_logger,
        FfiConverterOptionalString.lower(level))


def timestamp():
    return FfiConverterUInt64.lift(rust_call(_UniFFILib.uniffi_nostr_sdk_fn_func_timestamp,))


__all__ = [
    "InternalError",
    "NostrError",
    "NostrSdkError",
    "init_logger",
    "timestamp",
    "Keys",
    "Filter",
    "Event",
    "EventBuilder",
    "Contact",
    "AccountMetadata",
    "Client",
    "HandleNotification",
]

